### ISSUE TITLE
Support for D-Link DWA-182 Rev. D

### ISSUE THREAD

**Issue by MaxG87** [cilynx/rtl88x2BU_WiFi_linux_v5.2.4.4_25643.20171212_COEX20171012-5044#3] opened 2018-06-20 22:46 UTC
Hi,

I fixed the official D-Link driver for DWA-182 Rev. D for Linux 4.16, much like you did here. I had to fix the driver myself since your fixed driver seems to not support the DWA-182. However, your repository was a very big help. Thank you very much already.

I would like to merge both drivers as I do not see why there should be two repositories essentially doing the same thing. However, it seems to be quite an effort to align both drivers. Furthermore, while doing test merges, I noticed several conflicts I could not resolve due to a lack of domain knowledge.

Would you welcome such an effort? If yes, could you help me here and there?

Sincerely,

Max

**Comment by cilynx** [comment] 2018-06-21 01:19
Hi Max -- thanks for reaching out.  Did you try adding you D-Link card's identifier to [usb_intf.c](https://github.com/cilynx/rtl88x2BU_WiFi_linux_v5.2.4.4_25643.20171212_COEX20171012-5044/blob/master/os_dep/linux/usb_intf.c#L234-L240)?  Looking at your repo, [this](https://github.com/MaxG87/DWA-182_Rev-D1/blob/master/os_dep/linux/usb_intf.c#L237) is the line you need to bring over.  I'm curious to know if the driver here works with your card with that update.

It looks like D-Link provided you with a slightly newer driver base than the latest one I've seen: `v5.2.4.4_26334.20180126_COEX20171012-5044` vs `v5.2.4.4_25643.20171212_COEX20171012-5044`.  I'll start looking into the differences between the base versions and see what we need to do to get a single repo consolidated that works on both sides.

**Comment by cilynx** [comment] 2018-06-21 03:18
I pulled `v5.2.4.4_26334.20180126_COEX20171012-5044` from D-Link and backported the patches.  I confirmed that the Wsky adapters work with this driver.  Can you confirm if your DWA-182 Rev. D works?

https://github.com/cilynx/rtl88x2BU_WiFi_linux_v5.2.4.4_26334.20180126_COEX20171012-5044

**Comment by MaxG87** [comment] 2018-06-21 21:12
I think its better to continue the discussion over at the new repository.

**Comment by cilynx** [comment] 2018-06-22 00:56
Closing in favor of https://github.com/cilynx/rtl88x2BU_WiFi_linux_v5.2.4.4_26334.20180126_COEX20171012-5044/issues/2

**Closed as completed by cilynx** 2018-06-22 00:56 UTC
